### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by TruongDesign** [wswu/talking-piano-hophacks2020#2]
Occurs at generating PDF portion.

```
Traceback (most recent call last):
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\talking-piano-hophacks2020\src\webapp.py", line 33, in upload
    musescore_call.generate_pdf(dir_prefix + "-output.mid", dir_prefix + "-output.pdf")
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\talking-piano-hophacks2020\src\musescore_call.py", line 9, in generate_pdf
    subprocess.run(command)
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\theof\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by dghjunior** [comment]
@TruongDesign or @wswu is there an update on this? I am getting the same error at the moment
